[tool.poetry]
name = "flink"
version = "0.1.0"
description = ""
authors = ["Jun"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2 = "^2.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
